# Docker Build & Deploy
#
# Copy into your repository as .github/workflows/docker.yml (or use as a GitHub workflow template).

name: CI (docker)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  packages: write
  attestations: write

jobs:
  docker:
    uses: aerospike/shared-workflows/.github/workflows/reusable_docker-build-deploy.yaml@v2.0.3
    with:
      jf-project: my-project
      jf-build-name: my-app-container
      image-name: my-image
      app-name: My App
      app-version: 0.0.0-dev
      context: .
      file: ./Dockerfile
