version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /.github/workflows/execute-build/test_apps/DotnetHelloWorld/AerospikeHelloWorld/AerospikeHelloWorld
    schedule:
      interval: daily
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /.github/workflows/execute-build/test_apps/hi
    schedule:
      interval: daily
    groups:
      minor-and-patch:
        applies-to: version-updates
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /.github/workflows/execute-build/test_apps/NpmHelloWorld
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /.github/workflows/execute-build/test_apps/JavaHelloWorld
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /.github/workflows/execute-build/test_apps/GoHelloWorld
    schedule:
      interval: daily
