service {
    proto-fd-max 15000
}

__SECURITY__

network {
    service {
        address any
        port 3000
    }
    heartbeat {
        mode mesh
        port 3002
    }
    fabric {
        port 3001
    }
}

__NAMESPACE__
