service {
    feature-key-file /etc/aerospike/features.conf
    cluster-name docker
}

${SECURITY}

logging {
    console {
        context any info
    }
}

network {
    service {
        address any
        port 3000
    }
    heartbeat {
        mode mesh
        address any
        port 3002
        interval 150
        timeout 10
${MESH_SEEDS}
    }
    fabric {
        address any
        port 3001
    }
}

${NAMESPACE}
