namespace test {
    replication-factor __REPLICATION_FACTOR__
    strong-consistency true
    strong-consistency-allow-expunge true
    storage-engine device {
        file /opt/aerospike/data/test.dat
        filesize 4G
    }
}
