service {
    feature-key-file /etc/aerospike/features.conf
    cluster-name aerospike-tls
    proto-fd-max 15000
}

${SECURITY}

logging {
    console {
        context any info
    }
}

network {
    tls aerospike-tls {
        cert-file /etc/aerospike/tls/server.crt
        key-file  /etc/aerospike/tls/server.key
        ca-file   /etc/aerospike/tls/ca.crt
    }

    service {
        address any
        port 3000
        tls-port 4333
        tls-authenticate-client false
        tls-name aerospike-tls
    }
    heartbeat {
        mode mesh
        port 3002
    }
    fabric {
        port 3001
    }
}

${NAMESPACE}
