service {
    ${FEATURE_KEY_FILE}
    cluster-name docker
    proto-fd-max 15000
}

${SECURITY}

logging {
    console {
        context any info
    }
}

network {
${TLS_CONFIG}
    service {
        address any
        port 3000
${TLS_SERVICE}
    }
    heartbeat {
        mode mesh
        port 3002
    }
    fabric {
        port 3001
    }
}

${NAMESPACE}
