#!/usr/bin/env bats
# Maven bundle metadata (.maven-bundle-metadata.json) from type_detection.sh

load '../helpers/setup'

setup() {
    local _base="${BATS_TEST_TMPDIR:-${BATS_TMPDIR:-${TMPDIR:-/tmp}}}"
    mkdir -p "$_base"
    MAVEN_BUNDLE_TEST_DIR=$(mktemp -d "${_base%/}/maven-bundle.XXXXXX")
    export MAVEN_BUNDLE_TEST_DIR
}

teardown() {
    if [[ -n "${MAVEN_BUNDLE_TEST_DIR:-}" && -d "${MAVEN_BUNDLE_TEST_DIR}" ]]; then
        rm -rf "${MAVEN_BUNDLE_TEST_DIR}"
    fi
    unset MAVEN_BUNDLE_TEST_DIR || true
}

# detect_types.sh sources type_registry.sh (declare -A); requires bash 4+.
_require_bash4_for_detect_types() {
    ((BASH_VERSINFO[0] >= 4)) || skip "requires bash 4+ for detect_types (type_registry associative arrays)"
}

@test "maven bundle metadata: multi-module reactor (aggregator + child)" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts/maven"
    cat >"$wd/build-artifacts/maven/parent-1.0.0.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>parent-proj</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
  <modules>
    <module>child</module>
  </modules>
</project>
POM
    cat >"$wd/build-artifacts/maven/child-1.0.0.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>parent-proj</artifactId>
    <version>1.0.0</version>
  </parent>
  <artifactId>child</artifactId>
  <packaging>jar</packaging>
</project>
POM

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ -f "$meta" ]]
    [[ "$(jq -r .maven_module_count "$meta")" == "2" ]]
    [[ "$(jq -r .is_multi_package "$meta")" == "true" ]]
    [[ "$(jq -r .maven_aggregator_present "$meta")" == "true" ]]
    [[ "$(jq -r .is_flattened "$meta")" == "false" ]]
}

@test "maven bundle metadata: flatten-maven-plugin marker" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts"
    cat >"$wd/build-artifacts/consumer-1.0.0.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file was generated by the flatten-maven-plugin. -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>consumer</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
</project>
POM

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ "$(jq -r .maven_module_count "$meta")" == "1" ]]
    [[ "$(jq -r .is_flattened "$meta")" == "true" ]]
}

@test "maven bundle metadata: resolved-deps heuristic (no marker)" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts"
    cat >"$wd/build-artifacts/lib-2.0.0.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.flat</groupId>
  <artifactId>lib</artifactId>
  <version>2.0.0</version>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.9</version>
    </dependency>
  </dependencies>
</project>
POM

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ "$(jq -r .is_flattened "$meta")" == "true" ]]
    [[ "$(jq -r .maven_module_count "$meta")" == "1" ]]
}

@test "maven bundle metadata: no POMs yields zeros" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts"

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ -f "$meta" ]]
    [[ "$(jq -r .maven_module_count "$meta")" == "0" ]]
    [[ "$(jq -r .is_multi_package "$meta")" == "false" ]]
    [[ "$(jq -r .maven_aggregator_present "$meta")" == "false" ]]
    [[ "$(jq -r .is_flattened "$meta")" == "false" ]]
}
