#!/usr/bin/env bats
# Maven bundle metadata (.maven-bundle-metadata.json) from type_detection.sh

load '../helpers/setup'
load '../helpers/maven_fixtures'

setup() {
    local _base="${BATS_TEST_TMPDIR:-${BATS_TMPDIR:-${TMPDIR:-/tmp}}}"
    mkdir -p "$_base"
    MAVEN_BUNDLE_TEST_DIR=$(mktemp -d "${_base%/}/maven-bundle.XXXXXX")
    export MAVEN_BUNDLE_TEST_DIR
}

teardown() {
    if [[ -n "${MAVEN_BUNDLE_TEST_DIR:-}" && -d "${MAVEN_BUNDLE_TEST_DIR}" ]]; then
        rm -rf "${MAVEN_BUNDLE_TEST_DIR}"
    fi
    unset MAVEN_BUNDLE_TEST_DIR || true
}

# detect_types.sh sources type_registry.sh (declare -A); requires bash 4+.
_require_bash4_for_detect_types() {
    ((BASH_VERSINFO[0] >= 4)) || skip "requires bash 4+ for detect_types (type_registry associative arrays)"
}

@test "maven bundle metadata: multi-module reactor (aggregator + two children)" {
    _require_bash4_for_detect_types
    local wd meta target
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    create_jfrog_maven_fixture_tree "$wd"

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ -f "$meta" ]]
    [[ "$(jq -r .maven_module_count "$meta")" == "5" ]]
    [[ "$(jq -r .is_multi_package "$meta")" == "true" ]]
    [[ "$(jq -r .maven_aggregator_present "$meta")" == "true" ]]
    [[ "$(jq -r .is_flattened "$meta")" == "false" ]]

    target="$wd/structured_build_artifacts/jar/com/example/parent/parent-proj/1.0.0"
    [[ -f "$target/parent-proj-1.0.0.pom" ]]
    [[ -f "$target/parent-proj-1.0.0.pom.asc" ]]

    target="$wd/structured_build_artifacts/jar/com/example/parent/child-one/1.0.0"
    [[ -f "$target/child-one-1.0.0.pom" ]]
    [[ -f "$target/child-one-1.0.0.pom.asc" ]]

    grep -qE 'parent-proj-1\.0\.0\.pom[[:space:]]+jar$' "$wd/structured_build_artifacts/.manifest"
    grep -qE 'child-one-1\.0\.0\.pom[[:space:]]+jar$' "$wd/structured_build_artifacts/.manifest"
}

@test "maven bundle metadata: flatten-maven-plugin marker" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts"
    cat >"$wd/build-artifacts/consumer-1.0.0.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<!-- This file was generated by the flatten-maven-plugin. -->
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example</groupId>
  <artifactId>consumer</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
</project>
POM

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ "$(jq -r .maven_module_count "$meta")" == "1" ]]
    [[ "$(jq -r .is_flattened "$meta")" == "true" ]]
}

@test "maven bundle metadata: resolved-deps heuristic (no marker)" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts"
    cat >"$wd/build-artifacts/lib-2.0.0.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.flat</groupId>
  <artifactId>lib</artifactId>
  <version>2.0.0</version>
  <packaging>jar</packaging>
  <dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>2.0.9</version>
    </dependency>
  </dependencies>
</project>
POM

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ "$(jq -r .is_flattened "$meta")" == "true" ]]
    [[ "$(jq -r .maven_module_count "$meta")" == "1" ]]
}

@test "detect_types structures jar-less standalone POM with sidecars" {
    _require_bash4_for_detect_types
    local wd pom_dir f
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    pom_dir="$wd/build-artifacts"
    mkdir -p "$pom_dir"
    cat >"$pom_dir/standalone-bom.pom" <<'POM'
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.example.bom</groupId>
  <artifactId>standalone-bom</artifactId>
  <version>1.0.0</version>
  <packaging>pom</packaging>
</project>
POM
    echo "FAKE-GPG-SIGNATURE" >"$pom_dir/standalone-bom.pom.asc"
    md5sum "$pom_dir/standalone-bom.pom" >"$pom_dir/standalone-bom.pom.md5"
    sha1sum "$pom_dir/standalone-bom.pom" >"$pom_dir/standalone-bom.pom.sha1"
    write_gradle_module_metadata "$pom_dir/standalone-bom.module" \
        "com.example.bom" "standalone-bom" "1.0.0"
    echo "FAKE-GPG-SIGNATURE" >"$pom_dir/standalone-bom.module.asc"
    md5sum "$pom_dir/standalone-bom.module" >"$pom_dir/standalone-bom.module.md5"
    sha1sum "$pom_dir/standalone-bom.module" >"$pom_dir/standalone-bom.module.sha1"

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    pom_dir="$wd/structured_build_artifacts/jar/com/example/bom/standalone-bom/1.0.0"
    for f in standalone-bom.pom standalone-bom.pom.asc standalone-bom.pom.md5 standalone-bom.pom.sha1 \
             standalone-bom.module standalone-bom.module.asc standalone-bom.module.md5 standalone-bom.module.sha1; do
        [[ -f "$pom_dir/$f" ]] || (echo "Missing structured file: $pom_dir/$f" >&2 && return 1)
    done

    grep -qE 'standalone-bom\.pom[[:space:]]+jar$' "$wd/structured_build_artifacts/.manifest" || \
        (echo "standalone-bom.pom missing from manifest:" >&2 && cat "$wd/structured_build_artifacts/.manifest" >&2 && return 1)
    ! grep -qE 'standalone-bom\.(pom|module)\.(asc|md5|sha1)[[:space:]]' "$wd/structured_build_artifacts/.manifest"
    ! grep -qE 'standalone-bom\.module[[:space:]]' "$wd/structured_build_artifacts/.manifest"
}

@test "maven bundle metadata: no POMs yields zeros" {
    _require_bash4_for_detect_types
    local wd meta
    wd="${MAVEN_BUNDLE_TEST_DIR}/wd"
    mkdir -p "$wd/build-artifacts"

    (cd "$wd" && "$DEPLOY_ARTIFACTS_DIR/detect_types.sh" --artifacts-dir build-artifacts >/dev/null)

    meta="$wd/structured_build_artifacts/.maven-bundle-metadata.json"
    [[ -f "$meta" ]]
    [[ "$(jq -r .maven_module_count "$meta")" == "0" ]]
    [[ "$(jq -r .is_multi_package "$meta")" == "false" ]]
    [[ "$(jq -r .maven_aggregator_present "$meta")" == "false" ]]
    [[ "$(jq -r .is_flattened "$meta")" == "false" ]]
}
