name: Release
permissions:
  contents: write
  packages: write
  attestations: write
  id-token: write
on:
  workflow_dispatch:
  pull_request:
    branches: [main]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version: 20

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx -p semantic-release@24 \
              -p @semantic-release/commit-analyzer@13 \
              -p @semantic-release/release-notes-generator@14 \
              -p @semantic-release/github@11 \
              -p conventional-changelog@7 \
              -p conventional-changelog-conventionalcommits@8 \
              semantic-release
