name: Execute Build

permissions:
  contents: read
  id-token: write

on:
  workflow_call:
    inputs:
      # Required inputs
      project-directory:
        description: Directory where the dotnet project lives
        required: true
        type: string

jobs:
  execute-build:
    runs-on: ubuntu-latest
    steps:
      - run: cd ${ project-directory }
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Create nuget package
        shell: pwsh
        run: dotnet pack --no-build
