name: Execute Build

on:
  workflow_call:
    inputs:
      project:
        description: JFrog Artifactory project name
        required: true
        type: string
      build-name:
        description: Name for this build in artifactory
        required: true
        type: string
      build-version:
        description: Version for this build in artifactory
        required: true
        type: string
      build-script:
        description: Inline build script to execute
        required: false
        type: string
        default: ""
      build-script-path:
        description: Path to the build script to execute
        required: false
        type: string
        default: ""
      artifact-directory:
        description: Build script will place artifacts in this directory and it will be uploaded to github artifacts
        required: true
        type: string
      artifact-name:
        description: Name for artifacts from this build. Will be used for name of uploaded github artifacts
        required: false
        type: string
        default: build-artifacts
      retention-days:
        description: Retention days for the github artifacts
        required: false
        type: number
        default: 1
      artifactory-url:
        required: false
        description: JFrog Artifactory URL
        type: string
        default: https://aerospike.jfrog.io
      artifactory-oidc-provider-name:
        required: false
        description: OIDC provider name
        type: string
        default: gh-aerospike
      artifactory-oidc-audience:
        required: false
        description: OIDC audience
        type: string
        default: aerospike
      runs-on:
        description: The runner to use for the build
        required: false
        type: string
        default: ubuntu-22.04
      checkout-path:
        description: Directory to checkout the shared-workflows repository into
        required: false
        type: string
        default: shared-workflows
      source-repository:
        description: Repository to checkout for source code (format owner/repo)
        required: false
        type: string
        default: ${{ github.repository }}
      source-ref:
        description: Reference to checkout for source repository (branch, tag, or commit)
        required: false
        type: string
        default: ""
      source-path:
        description: Directory to checkout the source repository into
        required: false
        type: string
        default: local
      dry-run:
        description: Whether to run in dry-run mode
        required: false
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  execute-build:
    runs-on: ${{ inputs.runs-on }}
    env:
      CHECKOUT_REF: 722626ac96e0e8569ba587bd228b9468f6e49ead # Latest commit hash for development
    steps:
      - name: Checkout shared-workflows repository
        uses: actions/checkout@v4
        with:
          repository: aerospike/shared-workflows
          ref: ${{ env.CHECKOUT_REF }}
          path: ${{ inputs.checkout-path }}
          fetch-depth: 1

      - name: Checkout source repository
        if: inputs.source-path != ''
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.source-repository }}
          ref: ${{ inputs.source-ref }}
          path: ${{ inputs.source-path }}
          fetch-depth: 1

      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@2bc6e55719cd37dfb2f655a1e4f16c3440182a9f
        env:
          JF_URL: ${{ inputs.artifactory-url }}
          JF_PROJECT: ${{ inputs.project }}
        with:
          oidc-provider-name: ${{ inputs.artifactory-oidc-provider-name }}
          oidc-audience: ${{ inputs.artifactory-oidc-audience }}

      - name: Execute Build Script
        shell: bash
        run: |
          chmod +x ${{ inputs.checkout-path }}/.github/workflows/execute-build/entrypoint.sh
          dry_run_arg=""
          if [ "${{ inputs.dry-run }}" = "true" ]; then
            dry_run_arg="--dry-run"
          fi
          if [ "${{ inputs.build-script }}" != "" ]; then
            "${{ inputs.checkout-path }}/.github/workflows/execute-build/entrypoint.sh" \
              --build-script "${{ inputs.build-script }}" \
              --artifact-directory "${{ inputs.artifact-directory }}" \
              --build-name "${{ inputs.build-name }}" \
              --build-version "${{ inputs.build-version }}" \
              $dry_run_arg
          elif [ "${{ inputs.build-script-path }}" != "" ]; then
            "${{ inputs.checkout-path }}/.github/workflows/execute-build/entrypoint.sh" \
              --build-script-path "${{ inputs.build-script-path }}" \
              --artifact-directory "${{ inputs.artifact-directory }}" \
              --build-name "${{ inputs.build-name }}" \
              --build-version "${{ inputs.build-version }}" \
              $dry_run_arg
          else
            echo "Error: Either build-script or build-script-path must be given"
            exit 1
          fi

      - name: Upload Artifacts
        if: inputs.dry-run != true
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-directory }}
          retention-days: ${{ inputs.retention-days }}
