name: GPG sign file
on: workflow_dispatch
jobs:
  sign-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: setup GPG
        uses: ./devops/setup-gpg
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-key-pass: ${{ secrets.GPG_PASS }}
          gpg-key-name: "aerospike-inc"
   
      - name: GPG sign artifacts  # Signing other artifacts
        env:
          GPG_TTY: no-tty
          GPG_PASSPHRASE: ${{ secrets.GPG_PASS }}
        run: |
          gpg --detach-sign --no-tty --batch --yes --output README.md.asc --passphrase "$GPG_PASSPHRASE" README.md
          gpg --verify README.md.asc README.md
