name: GPG sign DEB
on: workflow_dispatch
jobs:
  sign-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: setup GPG
        uses: ./devops/setup-gpg
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-key-pass: ${{ secrets.GPG_PASS }}
          gpg-key-name: "aerospike-inc"

# It is required to use ether rpm or gpg directly to cache the password.
# This should be fixed in the future 
# You can instead use the --passphrase-file flag if you want

      - name: Sign and check rpm # gpg sign and verify rpm packages 
        env:
          GPG_TTY: no-tty
        # your rpm here
        run: |
          rpm --addsign tests/*.rpm
          rpm --checksig tests/*.rpm

      - name: GPG sign deb # gpg sign and verify deb packages
        env:
          GPG_TTY: no-tty
        run: |
          dpkg-sig --sign builder tests/*.deb
