name: GPG sign RPM
on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  sign-rpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: setup GPG
        uses: ./devops/setup-gpg
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-key-pass: ${{ secrets.GPG_PASS }}
          gpg-key-name: "aerospike-inc"
   
      - name: Sign and check rpm # gpg sign and verify rpm packages 
        env:
          GPG_TTY: no-tty
        # your rpm here
        run: |
          rpm --addsign tests/*.rpm
          rpm --checksig tests/*.rpm

