name: Test Docker Build-Deploy Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version override (leave empty for auto-detection)
        required: false
        default: ""
  pull_request:
    branches: [main]

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

concurrency:
  group: jfrog-test-deploy
  cancel-in-progress: false

jobs:
  extract-version:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Extract Version
        id: extract
        uses: ./.github/actions/extract-version-from-tag
        with:
          version: ${{ inputs.version }}
          version-file: .github/workflows/VERSION.example
    outputs:
      version: ${{ steps.extract.outputs.version }}
      git_tag: ${{ steps.extract.outputs.git_tag }}

  test-docker-build-deploy:
    uses: ./.github/workflows/reusable_docker-build-deploy.yaml
    needs: extract-version
    with:
      jf-project: test
      image-name: test-image
      app-version: ${{ needs.extract-version.outputs.version }}
      context: ./.github/workflows/execute-build/test_apps/hi
      file: ./.github/workflows/execute-build/test_apps/hi/Dockerfile
      jf-build-name: test-container
