name: GPG sign DEB
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
permissions: read-all
jobs:
  sign-deb:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-22.04
          #- ubuntu-24.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          egress-policy: audit

      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Check Ubuntu version
        # This action only supports Ubuntu 22.04. 24.04 has removed dpkg-sig
        run: |
          if [[ "$(cat /etc/lsb-release | grep DISTRIB_RELEASE)" != *"22.04"* ]]; then
            echo "This action only supports Ubuntu 22.04 due to the removal of dpkg-sig in 24.04"
            exit 1
          fi
        shell: bash
      - name: install dpkg-sig
        run: |
          sudo apt-get update && sudo apt-get install dpkg-sig dpkg-dev -y
      - name: setup GPG
        uses: aerospike/shared-workflows/.github/actions/setup-gpg@07c958ca4c5cea494dc8790949c08e3fb28c55e1 # v3.3.0
        with:
          gpg-private-key: ${{ secrets.GPG_SECRET_KEY }}
          gpg-public-key: ${{ secrets.GPG_PUBLIC_KEY }}
          gpg-key-pass: ${{ secrets.GPG_PASS }}

      - name: GPG sign deb # gpg sign and verify deb packages
        env:
          GPG_TTY: /dev/null
          HOME: /home/runner
          GNUPGHOME: /home/runner/.gnupg
        run: |
          # Ensure environment variables are exported
          export HOME="${HOME}"
          export GNUPGHOME="${GNUPGHOME}"

          # Sign the package
          dpkg-sig --sign builder --gpg-options "--batch --pinentry-mode loopback --passphrase-file $GNUPGHOME/passphrase" tests/*.deb
          # Verify the signature
          dpkg-sig --verify tests/*.deb
