name: Test Promote Release Bundle Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  test-promote-release-bundle-workflow:
    uses: ./.github/workflows/reusable_promote-release-bundle.yaml
    with:
      jf-project: test
      jf-bundle-name: test-release-bundle
      version: v1.0.0
      new-environment: TEST
      dry-run: true
