name: Test Upload Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  upload-test-gh-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Create Test Fixtures
        run: |
          .github/workflows/deploy-artifacts/create-test-fixtures.sh test-fixtures
      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: test-fixtures
          path: test-fixtures
  test-deploy-workflow:
    needs: upload-test-gh-artifacts
    uses: ./.github/workflows/reusable_deploy-artifacts.yaml
    with:
      jf-project: test
      jf-build-name: test-upload-workflow
      version: v1.0.0
      jf-build-id: ${{ github.run_number }}
      jf-metadata-build-id: ${{ github.run_number }}-metadata
      jf-url: https://artifact.aerospike.io
      oidc-provider-name: gh-aerospike
      oidc-audience: aerospike
      gh-artifact-name: test-fixtures
      dry-run: true
      gh-workflows-ref: bugfix/rpm-builds # use bugfix/rpm-builds once it is released

  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install dpkg-dev rpm -y
      - name: Test Entrypoint
        run: |
          .github/workflows/deploy-artifacts/test-entrypoint.sh
