name: Test Execute Build Dotnet Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  # execute-build:
  #     runs-on: ubuntu-latest
  #     steps:
  #       - run: cd ${ project-directory }
  #       - name: Restore dependencies
  #         run: dotnet restore
  #       - name: Build
  #         run: dotnet build --configuration Release --no-restore
  #       - name: Create nuget package
  #         shell: pwsh
  #         run: dotnet pack --no-build
  test-execute-build-workflow:
    uses: ./.github/workflows/reusable_execute-build.yaml
    with:
      jf-project: test
      jf-build-name: test-build
      jf-build-id: ${{ github.run_number }}-buildinfo-dotnet
      working-directory: repo-source/.github/workflows/execute-build/test_apps/DotnetHelloWorld
      build-script: |
        echo "Building dotnet project"
        dotnet restore
        dotnet build --configuration Release --no-restore
        echo "Creating nuget package"
        dotnet pack --no-build
        echo "Nuget package created"
        find .
      gh-source-path: repo-source
      gh-artifact-directory: build
      gh-artifact-name: build-artifacts-dotnet
      gh-retention-days: 1 # default
      oidc-provider-name: gh-dev-test
      oidc-audience: aerospike/testing
      dry-run: false # default
      gh-workflows-ref: v2.0.2
