name: Test Execute Build Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test-execute-build-workflow:
    uses: ./.github/workflows/reusable_execute-build.yaml
    with:
      jf-project: test
      jf-build-name: test-build
      jf-build-id: v1.0.0
      build-script: |
        echo "Need to ensure current-source is correctly present and building"
        cat current-source/README.md &&\
        cd project-location/.github/workflows/execute-build/test_apps/hi && make
      gh-checkout-path: project-location
      gh-source-path: current-source
      gh-artifact-directory: project-location/.github/workflows/execute-build/test_apps/hi/build
      gh-artifact-name: test-execute-build
      gh-retention-days: 1 # default
      jf-url: https://artifact.aerospike.io
      oidc-provider-name: gh-dev-test
      oidc-audience: aerospike/testing
      dry-run: false # default
      gh-workflows-ref: v2.0.1 # replace with v2.0.2 when it is released

  # Test the entrypoint script directly
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test Entrypoint
        run: |
          .github/workflows/execute-build/test-entrypoint.sh
