name: Test Upload Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  upload-test-gh-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: tests/test-1.0-2.noarch.rpm
  test-upload-workflow:
    uses: ./.github/workflows/reusable_upload-artifacts.yaml
    with:
      project: database
      build-name: test-upload-workflow
      version: v1.0.0
      artifactory-url: https://aerospike.jfrog.io
      artifactory-oidc-provider-name: gh-aerospike
      artifactory-oidc-audience: aerospike
      artifact-name: build-artifacts
      dry-run: true

  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install dpkg-dev rpm -y
      - name: Test Entrypoint
        run: |
          ${{ github.workspace }}/shared-workflows/.github/workflows/upload-artifacts/test-entrypoint.sh
