name: Test Execute Build Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test-execute-build-workflow:
    uses: ./.github/workflows/reusable_execute-build.yaml
    with:
      project: test
      build-name: test-build
      build-version: v1.0.0
      build-script: |
        echo "Need ensure current-source is correctly present and building"
        cat current-source/README.md &&\
        cd project-location/.github/workflows/execute-build/test_apps/hi && make
      checkout-path: project-location
      source-path: current-source
      artifact-directory: project-location/.github/workflows/execute-build/test_apps/hi/build
      artifact-name: test-execute-build
      retention-days: 1 # default
      artifactory-url: https://artifact.aerospike.io # default
      artifactory-oidc-provider-name: gh-aerospike # default
      artifactory-oidc-audience: aerospike # default
      dry-run: false # default

  # Test the entrypoint script directly
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Test Entrypoint
        run: |
          .github/workflows/execute-build/test-entrypoint.sh
