name: Test Execute Build Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  test-execute-build-workflow:
    uses: ./.github/workflows/reusable_execute-build.yaml
    with:
      jf-project: test
      jf-build-name: test-build
      jf-build-id: v1.0.0
      gh-workflows-ref: ${{ github.sha }}
      build-script: |
        echo "Need to ensure current-source is correctly present and building"
        cat current-source/README.md &&\
        cd project-location/.github/workflows/execute-build/test_apps/hi && make
      gh-checkout-path: project-location
      gh-source-path: current-source
      gh-artifact-directory: project-location/.github/workflows/execute-build/test_apps/hi/build
      gh-artifact-name: test-execute-build
      gh-retention-days: 1 # default
      jf-url: https://artifact.aerospike.io
      oidc-provider-name: gh-dev-test
      oidc-audience: aerospike/testing
      dry-run: false # default

  # Test the entrypoint script directly
  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@fe104658747b27e96e4f7e80cd0a94068e53901d # v2.16.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Test Entrypoint
        run: |
          .github/workflows/execute-build/test-entrypoint.sh
