name: Test Create Release Bundle Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  test-create-release-bundle-workflow:
    uses: ./.github/workflows/reusable_create-release-bundle.yaml
    with:
      jf-project: test
      jf-build-names: test-build-1:1728052628123,test-build-2:1728052628123
      jf-bundle-name: test-release-bundle
      version: v1.0.0
      jf-url: https://artifact.aerospike.io
      oidc-provider-name: gh-aerospike
      oidc-audience: aerospike
      dry-run: true

  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install jq -y
      - name: Test Entrypoint
        run: |
          .github/workflows/create-release-bundle/test-entrypoint.sh
