name: Test Upload Workflow
on:
  workflow_dispatch:
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  upload-test-gh-artifacts:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Create Test Fixtures
        run: |
          .github/workflows/deploy-artifacts/create-test-fixtures.sh test-fixtures
      - name: Upload Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-fixtures
          path: test-fixtures
  test-deploy-workflow:
    needs: upload-test-gh-artifacts
    uses: ./.github/workflows/reusable_deploy-artifacts.yaml
    with:
      gh-workflows-ref: ${{ github.sha }}
      jf-project: test
      jf-build-name: test-upload-workflow
      version: v1.0.0
      jf-build-id: ${{ github.run_number }}
      jf-metadata-build-id: ${{ github.run_number }}-metadata
      jf-url: https://artifact.aerospike.io
      oidc-provider-name: gh-aerospike
      oidc-audience: aerospike
      gh-checkout-path: . # Use current directory for internal calls
      # gh-checkout-path defaults to 'shared-workflows'
      gh-artifact-name: test-fixtures
      dry-run: true

  run-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install dpkg-dev rpm nodejs npm -y
      - name: Install bats
        run: |
          # Install bats-core from source (recommended method per official documentation)
          git clone https://github.com/bats-core/bats-core.git
          cd bats-core
          sudo ./install.sh /usr/local
          cd ..
          rm -rf bats-core
      - name: Run bats tests
        run: |
          cd .github/workflows/deploy-artifacts
          bats tests/bats/
